using System;

namespace TERMS_LOYALTY_API.Models
{
    public class TransactionDet
    {
        public long TransactionDetID { get; set; }
        public long ProductID { get; set; }
        public string ProductCode { get; set; }
        public string RefCode { get; set; }
        public long BarCodeFull { get; set; }
        public string? Descrip { get; set; }
        public string BatchNo { get; set; }
        public string SerialNo { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public decimal Cost { get; set; }
        public decimal AvgCost { get; set; }
        public decimal Price { get; set; }
        public decimal? Qty { get; set; }
        public decimal BalanceQty { get; set; }
        public decimal Amount { get; set; }
        public long UnitOfMeasureID { get; set; }
        public string? UnitOfMeasureName { get; set; }
        public decimal ConvertFactor { get; set; }
        public int IDI1 { get; set; }
        public decimal IDis1 { get; set; }
        public decimal IDiscount1 { get; set; }
        public long IDI1CashierID { get; set; }
        public int IDI2 { get; set; }
        public decimal IDis2 { get; set; }
        public decimal IDiscount2 { get; set; }
        public long IDI2CashierID { get; set; }
        public int IDI3 { get; set; }
        public decimal IDis3 { get; set; }
        public decimal IDiscount3 { get; set; }
        public long IDI3CashierID { get; set; }
        public decimal IDI4 { get; set; }
        public decimal IDis4 { get; set; }
        public decimal IDiscount4 { get; set; }
        public long IDI4CashierID { get; set; }
        public int IDI5 { get; set; }
        public decimal IDis5 { get; set; }
        public decimal IDiscount5 { get; set; }
        public long IDI5CashierID { get; set; }
        public decimal Rate { get; set; }
        public bool IsSDis { get; set; }
        public int SDNo { get; set; }
        public int SDID { get; set; }
        public decimal SDIs { get; set; }
        public decimal SDiscount { get; set; }
        public long DDisCashierID { get; set; }
        public decimal Nett { get; set; }
        public int LocationID { get; set; }
        public int DocumentID { get; set; }
        public int BillTypeID { get; set; }
        public int SaleTypeID { get; set; }
        public string Receipt { get; set; }
        public long SalesmanID { get; set; }
        public string? Salesman { get; set; }
        public long CustomerID { get; set; }
        public string? Customer { get; set; }
        public long CashierID { get; set; }
        public string? Cashier { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public DateTime RecDate { get; set; }
        public long BaseUnitID { get; set; }
        public int UnitNo { get; set; }
        public int RowNo { get; set; }
        public bool IsRecall { get; set; }
        public string? RecallNO { get; set; }
        public bool RecallAdv { get; set; }
        public decimal TaxAmount { get; set; }
        public bool IsTax { get; set; }
        public decimal TaxPercentage { get; set; }
        public bool IsStock { get; set; }
        public long UpdateBy { get; set; }
        public int Status { get; set; }
        public long ZNo { get; set; }
        public int GroupOfCompanyID { get; set; }
        public int DataTransfer { get; set; }
        public int CustomerType { get; set; }
        public int TransStatus { get; set; }
        public DateTime? ZDate { get; set; }
        public bool IsPromotionApplied { get; set; }
        public long PromotionID { get; set; }
        public int IsPromotion { get; set; }
        public int LocationIDBilling { get; set; }
        public int TableID { get; set; }
        public int OrderTerminalID { get; set; }
        public long TicketID { get; set; }
        public long OrderNo { get; set; }
        public bool IsPrinted { get; set; }
        public string? ItemComment { get; set; }
        public int Packs { get; set; }
        public bool IsCancelKOT { get; set; }
        public int StewardID { get; set; }
        public string? StewardName { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal ServiceChargeAmount { get; set; }
        public long ShiftNo { get; set; }
        public bool IsDayEnd { get; set; }
        public int UpdateUnitNo { get; set; }
        public long InvPriceLevelID { get; set; }
        public int Online { get; set; }
        public DateTime Deliverdate { get; set; }
        public decimal PackSize { get; set; }
        public string? TourAgentCode { get; set; }
        public int? TourAgentId { get; set; }
        public decimal? TourAmount { get; set; }
        public decimal? TourPrecent { get; set; }
        public decimal? TourCommition { get; set; }
        public decimal? TourCommitionPaidAmount { get; set; }
        public string? TourAgentCompanyCode { get; set; }
        public int TourAgentCompanyId { get; set; }
        public decimal TourCompanyAmount { get; set; }
        public decimal TourCompanyPrecent { get; set; }
        public decimal TourCompanyCommition { get; set; }
        public decimal TourCompanyCommitionPaidAmount { get; set; }
        public decimal Warranty { get; set; }
        public string? ItemSerial { get; set; }
        public decimal DelvryBalQty { get; set; }
        public bool IsBundleItem { get; set; }
        public int CreditPeriod { get; set; }
        public decimal CopperratePrice { get; set; }
        public bool IsCopperratePriceEnable { get; set; }
        public decimal SellingCopperratePrice { get; set; }
        public decimal AmountCopperratePrice { get; set; }
        public decimal NettCopperratePrice { get; set; }
        public decimal RateCopperratePrice { get; set; }
        public decimal PackPrice { get; set; }
        public bool IsPackSale { get; set; }
        public int NextBillDate { get; set; }
        public int PrinterType { get; set; }
        public int IsGLTransfer { get; set; }
        public decimal? FreeQty { get; set; }
        public bool DayEndComplete { get; set; }
        public decimal? ExchageQty { get; set; }
        public decimal? SubTotDisAmount { get; set; }
        public string? Remark { get; set; }
        public DateTime ExpiaryDate { get; set; }
        public int LoyaltyType { get; set; }
        public bool Ispacksize { get; set; }
        public int LastReading { get; set; }
        public string? CustomiseReceiptNo { get; set; }
        public string? Reasons { get; set; }
        public bool IsNewPrice { get; set; }
        public bool IsApproved { get; set; }
        public long ApprovedBy { get; set; }
        public string? ApprovedFor { get; set; }
        public string? TransactionSaleType { get; set; }
        public int? IsDeleted { get; set; }
        public decimal MinimumPrice { get; set; }
        public decimal MaximumPrice { get; set; }
        public decimal MaximumDiscountPercentage { get; set; }
        public decimal MaximumDiscount { get; set; }
        public decimal Margin { get; set; }
        public decimal WholesaleMargin { get; set; }
        public decimal GP { get; set; }
        public long DepartmentID { get; set; }
        public long CategoryID { get; set; }
        public long SubCategoryID { get; set; }
        public long SubCategory2ID { get; set; }
        public decimal WholesalePrice { get; set; }
        public string? WarrantyType { get; set; }
        public DateTime? LastRepair { get; set; }
        public bool IsWarranty { get; set; }
        public int WarrantyID { get; set; }
        public int DurationInMonths { get; set; }
        public DateTime WarrantyExpiryDate { get; set; }
        public bool IsCancelInvoice { get; set; }
        public bool IsShowRoomItem { get; set; }
        public bool IsWarrantyClaim { get; set; }
        public bool IsRefundEntireInvoice { get; set; }
        public bool IsTransferredToSAP { get; set; }
        public DateTime TransferredToSAP_Date { get; set; }
        public bool IsSync { get; set; }
        public long TemplateID { get; set; }
        public long InvoiceHeaderLevelID { get; set; }
        public string? UserName { get; set; }
        public string? AdmissionNo { get; set; }
        public long UserMobileNo { get; set; }
        public string? StudentGrade { get; set; }
        public string? BillRemark { get; set; }
        public string? DocEntry { get; set; }
        public string? DocNum { get; set; }
        public string? JobcardSerialNo { get; set; }
    }
}
